// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axaxcynwwpndnvdbjbow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4YXhjeW53d3BuZG52ZGJqYm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNDU3ODgsImV4cCI6MjA3NzgyMTc4OH0.qk9uhJ8V0hvzTX0gM3f7ZGSE1j6Y3vUYBjAr7DH6O7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});